# - name: Setup EC2 Instance
#   hosts: AnsibleKey
#   tasks:
#     - name: Install Python3-pip
#       apt:
#         name: python3-pip
#         state: present
#         update_cache: yes

- name: Setup EC2 Instance
  hosts: all
  tasks:
    - name: Install Python3-pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes