name: Ansible Deployment

on:
  push:
  workflow_dispatch:

env:
  ANSIBLE_HOSTKEY_CHECKING: false
  ANSIBLE_REMOTE_USER: ubuntu

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3

      - name: Install Ansible Galaxy Collection
        run: |
          ansible-galaxy collection install amazon.aws
          ansible-galaxy collection list

      - name: Verify amazon.aws collection
        run: |
          ansible-doc -t inventory amazon.aws.aws_ec2

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Debug - Check AWS credentials
        run: |
          aws sts get-caller-identity

      - name: Debug - List EC2 instances
        run: |
          aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Name`].Value|[0]]' --output table

      - name: Run Ansible inventory commands
        run: |
          ansible-inventory -i myinventory.aws_EC2.yml --list --yaml
          ansible-inventory -i myinventory.aws_EC2.yml --graph

      - name: Write SSH key to file
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > mykeyfile
          chmod 400 mykeyfile

      - name: Run Ansible playbook with verbose output
        run: |
          ansible-playbook -i myinventory.aws_EC2.yml --private-key mykeyfile playbook.yml -vvv